### PR TITLE
Fix thrift compile error in Linux environment

### PR DESCRIPTION
**Pull request by ilnoyoon**
Fix thrift compile error in case-insensitive Linux environment

### CODE REVIEW

**Comment by minwoo-jung** [comment]
@ilnoyoon
Ok i will review it.^^

**Comment by minwoo-jung** [comment]
@ilnoyoon 
Please explain more information. for example error message.

**Comment by ilnoyoon** [comment]
In my case, I ran 'build-thrift-linux.sh' without rename the flink.thrift file so I got the following message:

-----------------------------------------------------------------------------------------------------------
The ' characters around the executable and arguments are
not part of the command.
     [exec] Current OS is Linux
     [exec] Executing './src/compiler/linux/thrift-0.10.0' with arguments:
     [exec] '--gen'
     [exec] 'java:beans'
     [exec] '-o'
     [exec] '/home/ilnoyoon/git/ilnoyoon-pinpoint/thrift/generated-sources/thrift'
     [exec] '/home/ilnoyoon/git/ilnoyoon-pinpoint/thrift/src/main/thrift/Flink.thrift'
     [exec] 
     [exec] The ' characters around the executable and arguments are
     [exec] not part of the command.
Execute:Java13CommandLauncher: Executing './src/compiler/linux/thrift-0.10.0' with arguments:
'--gen'
'java:beans'
'-o'
'/home/ilnoyoon/git/ilnoyoon-pinpoint/thrift/generated-sources/thrift'
'/home/ilnoyoon/git/ilnoyoon-pinpoint/thrift/src/main/thrift/Flink.thrift'

The ' characters around the executable and arguments are
not part of the command.
     [exec] 
     [exec] [FAILURE:arguments:1] Could not open input file with realpath: /home/ilnoyoon/git/ilnoyoon-pinpoint/thrift/src/main/thrift/Flink.thrift
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------

I debugged and found that the 'flink.thrift' file started with a lowercase letter and replaced it with capital letters like any other thrift files.

**Comment by minwoo-jung** [comment]
Thank you for contribution.

**Pull request merged**
