### PR TITLE
[#6759] auto group agent if pinpoint.container.auto is set

### PR DESCRIPTION
**Pull request by yjqg6666**
If System Property pinpoint.container.auto is set to true, enable group agent feature automatically when running in docker/container environment.

### CODE REVIEW

**Comment by emeroad** [comment]
@yjqg6666
Thank you for your contribution

**Comment by minwoo-jung** [comment]
That's a good idea.
I will review it this week.

**Comment by minwoo-jung** [comment]
ref : https://github.com/naver/pinpoint/issues/6759

**Comment by minwoo-jung** [comment]
@yjqg6666 

I reviewed it and made some changes to the code as there are good things to improve. 

The pinpoint.container.auto option has been removed,
and if there is no pinpoint.container option, it can be automatically detected by checking the .dockerenv file or KUBERNETES_SERVICE_HOST.


How do you think about this? I pushed it to your repository. If you think it's okay, I will merge.

**Comment by yjqg6666** [comment]
Good. I add this option is just for backward-compatibility. I'm quite OK with it for removing this option, it's sort of redundant.

**Comment by yjqg6666** [comment]
@minwoo-jung Thanks for the improvement.

**Pull request merged**
