### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by KimTaehee**
Hi. I found some misspellings on your source codes.
I think they're less important except for CSS.

### CODE REVIEW

**Comment by lioolli** [comment]
Thanks for your contribution. I have commented about coding convention at your commit. Please check it out.

**Comment by lioolli** [comment]
We don't have coding style doc because space indentaion is the only convention. : )

**Comment by nstopkimsk** [comment]
thank you for your contributions.

**Comment by KimTaehee** [comment]
@nstopkimsk  @lioolli  You're welcome. I'd like to express my gratitude to your quick update.

**Pull request merged**
