### PR TITLE
1.8.x

### PR DESCRIPTION
**Pull request by xiaojinde**
resolve the issue: kafka have multi-client,link don't show all kafka's consumer

### CODE REVIEW

**Comment by xiaojinde** [comment]
hi,pinpoint team.i have modified a little codes,for resolve the issue:kafka have multi-client,link don't show  all kafka's consumer.i hopes contribution to a power for pinpoint!

**Comment by koo-taejin** [comment]
hi @xiaojinde 

Please tell me about this PR.

This PR is related to #5793?
If I do backport that #5807 issue, will the problem be solved?
If not, please explain in detail what is lacking in the #5807 issue.

thanks.

**Comment by xiaojinde** [comment]
@koo-taejin, hi.
yes, this pr is related to  #5793. i modify this issue by my method on the 1.8.4 branch.i don't test your code.so I don't know if have any lacking. i think we can learn from each other.

**Comment by koo-taejin** [comment]
@xiaojinde 

It does not seem good to have different code  for a same Feature. 
Thank you very much for your enthusiasm, but I can't not merge this PR.

**Comment by xiaojinde** [comment]
ok,thanks!

**Comment by xiaojinde** [comment]
@koo-taejin ,please look this pr:remove NullPointerException problem #5921.

**Comment by koo-taejin** [comment]
@xiaojinde 

I think it would be better for the person who developed the code
@jaehong-kim Please review #5921 pull request

**Pull request closed without merging**
