### PR TITLE
Support collect detailed exception stacktrace by config

### PR DESCRIPTION
**Pull request by IluckySi**
Support collect detailed exception stacktrace by config
related to https://github.com/naver/pinpoint/pull/7158

### CODE REVIEW

**Comment by IluckySi** [comment]
@emeroad Hello， Woonduk， I need you to see if there is any problem with this pr，Thank you~
detailed description：https://github.com/naver/pinpoint/pull/7158

**Comment by emeroad** [comment]
@IluckySi 
Thank you for your contribution.

https://github.com/naver/pinpoint/pull/7165/files#diff-77f872e60c9d162a6ff1fed372a91cceR26

What do you think of migrating `XXXInterceptor.processThrowable` method to `AbstractRecorder.recordException` method?

**Comment by IluckySi** [comment]
> @IluckySi
> Thank you for your contribution.
> 
> https://github.com/naver/pinpoint/pull/7165/files#diff-77f872e60c9d162a6ff1fed372a91cceR26
> 
> What do you think of migrating `XXXInterceptor.processThrowable` method to `AbstractRecorder.recordException` method?

I thought so before, but I found that I cannot get Profilerconfig  in AbstractRecorder.recordException method~

**Comment by IluckySi** [comment]
@emeroad 
What do you think of Changing DefaultProfilerConfig to a SingleTon，
So I can use DefaultProfilerConfig in AbstractRecorder.recordException method，
Do you have any suggestions，Thank you~

` public static DefaultProfilerConfig getInstance () {
        return getInstance(null);
    }

    public static DefaultProfilerConfig getInstance (Properties properties) {
        if (defaultProfilerConfig == null) {
            synchronized(DefaultProfilerConfig.class) {
                if (defaultProfilerConfig == null) {
                    defaultProfilerConfig = new DefaultProfilerConfig(properties);
                }
            }
        }
        return defaultProfilerConfig;
    }

    // For test
    public DefaultProfilerConfig() {
        this.properties = new Properties();
        this.thriftTransportConfig = new DefaultThriftTransportConfig();
    }

    // For test
    public DefaultProfilerConfig(Properties properties) {
        if (properties == null) {
            throw new NullPointerException("properties");
        }
        this.properties = properties;
        readPropertyValues();
    }`

**Comment by tankilo** [comment]
Should the root cause of the exception to be record before outside exception?
Sometimes, exception may be throwed from inner methods which are not intercepted and then intercepted by outer methods, the root cause contain the most useful message.

By the way, i think tracing and logging should be considered separately. You can find the full exception stacktrace with traceId in log center.

**Comment by emeroad** [comment]
I think logging and tracing should be tightly integrated.
It would be ideal to store the exceptions in a separate table and display the timeline.

**Comment by IluckySi** [comment]
In the future, I will try to save the exception stack information in an HBase table separately ~ 
the perspective of log tool and APM tool in analyzing application performance problems is different.  They are complementary. The analysis of request exception is an important function for both log tool and APM tool.

**Pull request closed without merging**
