### PR TITLE
Elasticsearch Client Plugin Contribution

### PR DESCRIPTION
**Pull request by yin-bp**
Title: Elasticsearch Client Plugin Contribution

Link: https://github.com/yin-bp/pinpoint/tree/master/plugins/elasticsearch-bboss
Target: Elasticsearch Client Java API BBoss
Supported Version: All Elasticsearch version,BBoss version 5.0.9.8,pinpoint 1.8.x
Description: This agent plugin is worked with elasticsearch rest client BBoss,
BBoss is a best Java Highlevel Rest client for ElasticSearch.

ServiceTypes: [1971, "ElasticsearchBBoss"],[1972, "ElasticsearchBBossEvent"],[9977, "ElasticsearchBBossExecutor"]
Annotations: [971, "es.args"],[972, "es.url"],[973, "es.dsl"],[974, "es.action"],[975, "es.responseHandle"],[976, "es.version"]
Configurations: List of configuration keys and description the plugin adds.

profiler.elasticsearchbboss.enabled=true //enable or disable this plugin, default true.
profiler.elasticsearchbboss.recordResult=false //record or disable record method return value ,default false.
profiler.elasticsearchbboss.recordArgs=true //record or disable record method args,default true.

### CODE REVIEW

**Comment by RoySRose** [comment]
Hello, @yin-bp 

Elasticsearch BBoss Client was scheduled to be merged to 1.8.1.
and since 1.8.0 is released. I am trying to test and merge this pull request.

Can you resolve the conflicts first?

**Comment by yin-bp** [comment]
Ok，I'm going to resolve these conflicts soon.

**Comment by yin-bp** [comment]
Hi,@RoySRose 
this is move to PR #4666

**Comment by RoySRose** [comment]
@yin-bp 
Got it, I'm away for a business trip until next WED. I'll take a look at it as soon as I get back:)  Thanks.

**Pull request closed without merging**
