### PR TITLE
fix period-selector maxPeriodTime issue

### PR DESCRIPTION
**Pull request by yjqg6666**
1. Change the MAX_SEARCH_PERIOD hint message from days unit to hours unit. Please verify that the I18n text(hours= 시간) is correct. Using hours may be more convenient.
2. The maxPeriod value could be read from getMaxPeriodTime config, it was the last value of periodList.

### CODE REVIEW

**Comment by binDongKim** [comment]
What made you think using/displaying the hint message with hours is more convenient? As you can see from the interface, the period-list is listed as `5m / 20m / ... / 2d ` so the hint message with `2d` seems consistent in my opinion.

**Comment by yjqg6666** [comment]
In production environment, we may restrict to use too long time span/period, 2 days or more may cause many hbase lookups, hours may be preferred.

**Comment by yjqg6666** [comment]
If the maxPeriodTime is 6 hours, the message would be 0.25 day. If 3 hours, then 0.125 day.

**Comment by binDongKim** [comment]
I don't understand. The maxPeriodTime has set as `2days` as a static value(or `7days` in inspector page) so the message would be never anything other than `2days`(or `7days`).

**Comment by yjqg6666** [comment]
@binDongKim Updated the PR, only include "honor the getMaxPeriodTime static config".

**Pull request closed without merging**
