### PR TITLE
Add unit tests for com.navercorp.pinpoint.rpc.util MapUtils and ListUtils

### PR DESCRIPTION
**Pull request by Braavos96**
I've analysed your codebase and noticed that `com.navercorp.pinpoint.rpc.util MapUtils` and `ListUtils` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.

### CODE REVIEW

**Comment by Braavos96** [comment]
Hi, I tried to sign your CLA and for some reason there seems to be an error with it stating there is no CLA to sign

**Comment by Xylus** [comment]
Hi @Braavos96 
The CLA link seems to be working okay, could you give it another go?
The agreement itself may take a few seconds to load.

**Comment by Braavos96** [comment]
Hi @Xylus I have signed the CLA. It kept giving me an error when I clicked on it for some reason.

**Comment by Braavos96** [comment]
Hi @Xylus just following up and wondering if you would like me to make any changes to the PR?

**Comment by Xylus** [comment]
Hi @Braavos96 
Sorry this has completely slipped my mind.
Let me check back once the CI build is finished.

**Comment by Braavos96** [comment]
Hi @Xylus 
Thank you :)

**Comment by Xylus** [comment]
@Braavos96 Thank you for your contribution!

**Pull request merged**
