### PR TITLE
Change DefaultProfilerConfig to a SingleTon

### PR DESCRIPTION
**Pull request by IluckySi**
Change DefaultProfilerConfig to a SingleTon,
So I can use DefaultProfilerConfig in AbstractRecorder.recordException method for record detailed exception with config。

### CODE REVIEW

**Comment by IluckySi** [comment]
@emeroad 
Do you think there is any problem with this way？ Thank you~

**Comment by emeroad** [comment]
We avoid using the singleton pattern whenever possible.
It is recommended to inject the object from the guice container.

**Comment by IluckySi** [comment]
> container
OK, thank you. I'll think about it again

**Comment by emeroad** [comment]
The recommended pattern is below.
```java
public class DefaultRecorderFactory implements RecorderFactory {
    private ProfilerConfig config;
    private final StringMetaDataService stringMetaDataService;
    private final SqlMetaDataService sqlMetaDataService;
    private final Provider<AsyncContextFactory> asyncContextFactoryProvider;
    private final IgnoreErrorHandler errorHandler;

    @Inject
    public DefaultRecorderFactory(ProfilerConfig config, //<---  ProfilerConfig is injected from the guice.
                                  Provider<AsyncContextFactory> asyncContextFactoryProvider,
                                  StringMetaDataService stringMetaDataService, SqlMetaDataService sqlMetaDataService, IgnoreErrorHandler errorHandler) {
        this.config = Assert.requireNonNull(config, "config");

        this.asyncContextFactoryProvider = Assert.requireNonNull(asyncContextFactoryProvider, "asyncContextFactoryProvider");
        this.stringMetaDataService = Assert.requireNonNull(stringMetaDataService, "stringMetaDataService");
        this.sqlMetaDataService = Assert.requireNonNull(sqlMetaDataService, "sqlMetaDataService");
        this.errorHandler = Assert.requireNonNull(errorHandler, "errorHandler");
    }
```

**Comment by IluckySi** [comment]
Thank you very much. I'll try~

**Pull request closed without merging**
