### PR TITLE
Elasticsearch Client Plugin Contribution

### PR DESCRIPTION
**Pull request by yin-bp**
Title: Elasticsearch Client Plugin Contribution

Link: https://github.com/yin-bp/pinpoint/tree/master/plugins/elasticsearch-bboss
Target: Elasticsearch Rest Client BBoss
Supported Version: pinpoint 1.9.0
Description: This agent plugin is worked with elasticsearch rest client BBoss,BBoss is a best Java Highlevel Rest client for ElasticSearch.

ServiceTypes: [9201, "ElasticsearchBBoss"],[9202, "ElasticsearchBBossExecutor"]
Annotations: [971, "es.args"],[972, "es.url"],[973, "es.dsl"],[974, "es.action"],[975, "es.responseHandle"],[976, "es.version"]

Configurations: List of configuration keys and description the plugin adds.

profiler.elasticsearchbboss.enabled=true //enable or disable this plugin, default true.
profiler.elasticsearchbboss.recordResult=false //record or disable record method return value ,default false.
profiler.elasticsearchbboss.recordArgs=true //record or disable record method args,default true.
profiler.elasticsearchbboss.recordDsl=true //record or disable record dsl,default true.
profiler.elasticsearchbboss.recordESVersion=true //record or disable record ES Version infomation,default true.
profiler.elasticsearchbboss.recordResponseHandlerClass=false //record or disable record response handle class ,default false.
profiler.elasticsearchbboss.maxDslSize=50000 //set the max length dsl script,over this size dsl will be substring.

### CODE REVIEW

**Comment by yin-bp** [comment]
Hi,@RoySRose:
 Elasticsearch bboss plugin has been refactored.
Some runtime pictures of this plugin:
Elasticsearch Bboss work in tomcat
GitHub Logo
GitHub Logo
Async parallel slice scoll query
GitHub Logo
Simple indice and indice type exist query
GitHub Logo
dsl query
GitHub Logo

**Comment by yin-bp** [comment]
@RoySRose 
To disable httpclient4 trace，The follow two method have been added to [Trace ](https://github.com/yin-bp/pinpoint/blob/master/bootstrap-core/src/main/java/com/navercorp/pinpoint/bootstrap/context/Trace.java) interface:

```java
/**
     * Pause the trace sampled.
     * In some scenarios, it is necessary to pause the plug-in interception work related to the method internal logic.
     * When the method internal logic is executed, the after interception work of this method is continued. For example,
     * ElasticSearch Bboss plugin as a terminal plugin needs to shield the underlying HTTP protocol plugin
     */
    void pauseSampled();
    /**
     * Continue the paused trace sampled.
     * In some scenarios, it is necessary to pause the plug-in interception work related to the method internal logic.
     * When the method internal logic is executed, the after interception work of this method is continued. For example,
     * ElasticSearch Bboss plugin as a terminal plugin needs to shield the underlying HTTP protocol plugin
     */
    void resumeSampled();
```

pauseSampled/resumeSampled have been used in ElasticsearchExecutorOperationInterceptor:

```java
 @Override
    public void before(Object target, Object[] args) {
        super.before(target,args);
        Trace currentTrace = traceContext.currentTraceObject();
        if(currentTrace != null ){

            currentTrace.pauseSampled();
        }
    }
    @Override
    public void after(Object target, Object[] args, Object result, Throwable throwable)     {

        Trace currentTrace = traceContext.currentRawTraceObject();
        if(currentTrace != null){

            currentTrace.resumeSampled();
        }
        super.after(target,args,result,throwable);
    }
```

**Comment by yin-bp** [comment]
How to use Elasticsearch BBoss.

First add the maven dependency of BBoss to your pom.xml:

```xml
       <dependency>
            <groupId>com.bbossgroups.plugins</groupId>
            <artifactId>bboss-elasticsearch-rest-jdbc</artifactId>
            <version>5.2.7</version>
        </dependency>
```

If it's a spring boot project, you can replace the Maven coordinates above with the following Maven coordinates:

```xml
        <dependency>
            <groupId>com.bbossgroups.plugins</groupId>
            <artifactId>bboss-elasticsearch-spring-boot-starter</artifactId>
            <version>5.2.7</version>
        </dependency>
```



Second add following elasticsearch addresses to the config file application.properties in your project resources diretory:

```properties
elasticsearch.rest.hostNames=10.21.20.168:9200

#Cluster addresses are separated by commas

#elasticsearch.rest.hostNames=10.180.211.27:9200,10.180.211.28:9200,10.180.211.29:9200
```



And last  create a jsp file named testElasticsearch.jsp :

```jsp
<%@ page import="org.frameworkset.elasticsearch.ElasticSearchHelper" %>
<%@ page import="org.frameworkset.elasticsearch.client.ClientInterface" %>
<%@ page import="org.frameworkset.elasticsearch.entity.ESDatas" %>
<%@ page import="org.frameworkset.elasticsearch.scroll.ScrollHandler" %>
<%@ page import="java.util.List" %>
<%@ page import="java.util.Map" %>
<%@ page import="com.frameworkset.common.poolman.SQLExecutor" %>
<%@ page language="java" pageEncoding="UTF-8"%>

<%
	ClientInterface clientUtil = ElasticSearchHelper.getRestClientUtil();
	//get elasticsearch cluster state
	String result = clientUtil.executeHttp("_cluster/state?pretty",ClientInterface.HTTP_GET);

	//check indice twitter and index type tweet exist or not.
	boolean exist1 = clientUtil.existIndiceType("twitter","tweet");
	out.println("twitter  tweet type exist:"+exist1);
	//check indice twitter exist or not
	exist1 = clientUtil.existIndice("twitter");
	out.println("twitter exist:"+exist1);
	//count documents in indice twitter
	long count = clientUtil.countAll("twitter");
	out.println(count);

	//Get All documents of indice twitter,DEFAULT_FETCHSIZE is 5000
	ESDatas<Map> esDatas = clientUtil.searchAll("twitter", Map.class);

	//Get All documents of indice twitter,Set fetchsize to 10000, Using ScrollHandler to process each batch of datas.
	clientUtil.searchAll("twitter",10000,new ScrollHandler<Map>() {
		public void handle(ESDatas<Map> esDatas) throws Exception {
			List<Map> dataList = esDatas.getDatas();
			System.out.println("TotalSize:"+esDatas.getTotalSize());
			if(dataList != null) {
				System.out.println("dataList.size:" + dataList.size());
			}
			else
			{
				System.out.println("dataList.size:0");
			}
			//do something other such as do a db query.
			SQLExecutor.queryList(Map.class,"select * from td_sm_user");
		}
	},Map.class);
    //Use slice parallel scoll query all documents of indice  twitter by 2 thread tasks. DEFAULT_FETCHSIZE is 5000
	//You can also use ScrollHandler to process each batch of datas on your own.
	clientUtil.searchAllParallel("twitter", Map.class,2);
	out.println("searchAllParallel:ok");
%>

```

Put the file into the web project that has been connected to pinpoint, run the program, log on pinpoint to see the execution effect of bboss plug-in.

**Comment by RoySRose** [comment]
Hello, @yin-bp 

Sorry for such a late reply. I was caught up with personal things.
Most of all, I'm thrilled to take a look at how you took care of the duplicate of http4.
Also, it's great to see ElasticsearchBBoss Client Plugin getting better and better.

I'll take a look ASAP :)

**Comment by yin-bp** [comment]
Hi,@RoySRose:
By adjusting the value of the sampling attribute to mask the httpclient4 data collection so as to prevent the problem of trace log repeat collection, I would like to ask if there is a better way to deal with this problem.
Thank you very much!

**Comment by yin-bp** [comment]
Hi,@RoySRose :
Is there any problem with the plugin or is there any improvement that needs to be made and can the merge request be processed?

**Comment by RoySRose** [comment]
@yin-bp 

I'm keep getting distracted with other works on me.

Currently, I'm looking into bboss library and almost understood your plug-in codes.
I'm trying to create a simple sample application that used bboss to test a few things.

I didn't fully review `pauseSampled/resumeSampled` logic yet.
There are different opinions in my team on pausing the trace. There are suggestions to show the duplication made by HTTP4, which will make tracings much clear to users. I'll let you know if it gets more solid.

1. What do YOU think about the duplication? 

2. I've found a few methods that are not in use, which can be deleted. such as 
 - ElasticsearchPlugin.getClazzInterceptors()
 - ElasticsearchBaseOperationInterceptor.mergeParameterVariableNameDescription()
 - It would be great if you can take care of other non-used methods.

3. Below is only used in the test. Is there be any way to replace the method to somewhere under test?
- ElasticsearchBaseOperationInterceptor.convertParams()

4. Since v1.9.0, we are trying to change how interceptors are called. 
As you can see below the `transform` method has been deprecated.
This is not necessary but, but it would be great if you can change by referring to other plugins.

image

5. I was wondering if `ElasticsearchBaseOperationInterceptor` class can be removed.
If you take care of 2 and 3, above. I think `ElasticsearchBaseOperationInterceptor` is exactly the same as  `com.navercorp.pinpoint.bootstrap.interceptor.SpanEventSimpleAroundInterceptorForPlugin`.
EXCEPT! below part
```java
if(!isTraceMethod())
	return ;
```
BUT, I think this can be replaced and taken care of insided `com.navercorp.pinpoint.plugin.elasticsearchbboss.ElasticsearchPlugin`
by, NOT calling the intercepting class for those methods. (such as rejecting from `ElasticsearchCustomMethodFilter`)

6. About `ElasticsearchCustomMethodFilter`. With our experience on plugins. We HIGHLY SUGGEST maintaining whitelist rather than a blacklist.  
It recommeneded to specify the name of method that needs to be instrumented.

For example. 
CassandraPlugin
image

MongoDBPlugin
image

Within this way plugin's potential errors when the library is updated to a new version(in this case bboss) are abruptly reduced.

Hope I'm not asking you too much 😅

Once again, sorry for such a late reply.

**Comment by RoySRose** [comment]
Oh, one more 

7. can you reduce the git commit to few commits that has meaning? by merging the commits.
also, since pinpoint project has rebase policy. 

Just mentioning in case you wondering what I meant by rebase.
https://github.com/naver/pinpoint-docker/pull/11#issuecomment-463546974

I'll 
1. try to make a sample app.
2. review `pausing` and get some results.
3. review on Integration Tests (ElasticsearchExecutorIT and more..)

**Comment by yin-bp** [comment]
> 2\. deleted

Thank you very much for giving me so many reasonable Suggestions for improvement. I will accept your Suggestions as soon as possible

**Comment by yin-bp** [comment]
@RoySRose 
Thank you very much for giving me so many reasonable Suggestions for improvement. 
First I will accept your suggestions in 2,3,4,5,6,7 as soon as possible.Then I'll check different opinions in your team on pausing the trace in 1.

**Comment by yin-bp** [comment]
Hi,@RoySRose:
Refactor Trace #5229 removes sampling variable from Trace object:

```
public boolean canSampled () {

	return true;

}
```

So now pauseSampled/resumeSampled can't work, how to do to avoid http4 repeat monitoring data.

**Comment by RoySRose** [comment]
Hello, @yin-bp 

Due to your last reply about `removed sampling variable`.
Majority of team members thinks duplication of the data is rather necessary since it will be more obvious to the users.
So, contrary to my first suggestion(I'm sorry about this 😓), I think you can just drop the pausing part.

**Comment by yin-bp** [comment]
Hello, @RoySRose:
If duplicate HTTP records are not forbidden, duplicate HTTP nodes will be generated in the top graph:
duplicateHTTPnodes

**Comment by RoySRose** [comment]
@yin-bp 

I can't run the example given above
https://github.com/naver/pinpoint/pull/5050#issuecomment-450089347

do you have any simple(just CRUD is enough) java bboss application? with controller-service-dao pattern?

**Comment by yin-bp** [comment]
> @yin-bp
> 
> I can't run the example given above
> [#5050 (comment)](https://github.com/naver/pinpoint/pull/5050#issuecomment-450089347)
> trouble with indexes.
> 
> do you have any simple(just CRUD is enough) java bboss application? with controller-service-dao pattern?
@RoySRose :
ok,I'll give you one. Just a moment

**Comment by yin-bp** [comment]
> @yin-bp
> 
> I can't run the example given above
> [#5050 (comment)](https://github.com/naver/pinpoint/pull/5050#issuecomment-450089347)
> trouble with indexes.
> 
> do you have any simple(just CRUD is enough) java bboss application? with controller-service-dao pattern?

@RoySRose Web service demo based on spring boot 2 and Elasticsearch bboss client 5.3.8
https://github.com/bbossgroups/es_bboss_web

**Comment by RoySRose** [comment]
@yin-bp 

I have an idea to remove duplicate HTTP nodes?
Few modifications and test are needed to check if it works.
I'll check out on this next week and let you know

**Comment by BillLucky** [comment]
Hello everyone, is there any progress in this issue? We also want to use this feature 😁

**Comment by RoySRose** [comment]
Trying to take care of duplication in the server map.
But looks like this is going to take some time.
Other than this.
It's up to yin-bp

**Comment by RoySRose** [comment]
Hello, @yin-bp

I know it's been a while on this issue. 
I'm not sure if you're going to follow-up on this again.
But, like to notify you on #5506 Alias Feature PR.

This added feature will take care of duplicated HTTP records
Even after dropping the pausing part.

**Comment by yin-bp** [comment]
Thank you very much,that's great,I'll take the new feature to make Elasticsearch client plugin work right.

**Comment by RoySRose** [comment]
@yin-bp 

 notifying you that #5506 Alias Feature has been merged to the master.

**Comment by yin-bp** [comment]
> @yin-bp
> 
> notifying you that #5506 Alias Feature has been merged to the master.

I'll try this feature out on Elasticsearch client bboss pluin as soon

**Comment by yin-bp** [comment]
Hi,@RoySRose:
Elasticsearch Bboss Client plugin has used ServiceType AS_ALIAS without RECORD_STATISTICS and now it is work right. Thank you and your team's great job.

**Comment by RoySRose** [comment]
@yin-bp 

Great~! Good to hear it's working correctly.
Let me know if the plug-in is ready to be reviewed :)

**Comment by yin-bp** [comment]
> @yin-bp
> 
> Great~! Good to hear it's working correctly.
> Let me know if the plug-in is ready to be reviewed :)

Yes,It's ready to be reviewed!

**Comment by RoySRose** [comment]
@yin-bp

I think I've mentioned something similar a few months ago.
1. There are too many commits and also non-necessary ones.
 - please combine commits which are possible.
 - commits by others don't have to be committed in this PR (I think this will be taken care of if you try to rebase instead of merge.)

2. This branch should be possible for `rebase and merge`
Currently, it's not.
image

Please check the above issues. I'll start reviewing the code right after.

**Comment by yin-bp** [comment]
> @yin-bp
> 
> I think I've mentioned something similar a few months ago.
> 
> 1. There are too many commits and also non-necessary ones.
> 
> * please combine commits which are possible.
> * commits by others don't have to be committed in this PR (I think this will be taken care of if you try to rebase instead of merge.)
> 
> 1. This branch should be possible for `rebase and merge`
>    Currently, it's not.
>    image
> 
> Please check the above issues. I'll start reviewing the code right after.

Okey,to many commit to handle , I'll checkout this use a new pull request.

**Comment by RoySRose** [comment]
@yin-bp 

Well. There are several ways to handle this.
But! since there are TOO many commits already.

I'd restart in a clean sheet if I were you.
Since code that changed are very isolated to a certain location.
1. save the codes to your local machine.
2. pull the latest master to a new branch
3. put the saved code on the new branch
4. rebase in case there are changes in upstream/master

I think this is the clearest way.

**Comment by yin-bp** [comment]
@RoySRose 👍 
Ok, I'll take your advice.

**Comment by yin-bp** [comment]
Hi,@RoySRose
This has been move to  the new pull request Elasticsearch Client Plugin Contribution #5546

**Pull request closed without merging**
