### PR TITLE
Dev plugin rabbitmq

### PR DESCRIPTION
**Pull request by wuyipei**
最近有需求在做rabbitmq的调用链跟踪，谢谢！

### CODE REVIEW

**Comment by Xylus** [comment]
Hi @wuyipei @majinkai @jiaqifeng 
Thanks for continuing the work on the rabbitmq plugin.
Would it be possible to rebase the branch onto the current master branch? This will make the whole PR process a lot more simple.

**Comment by jiaqifeng** [comment]
@Xylus 
I have re-create the branch based on master. But it seems something goes wrong. Shoud I rebase on master or any branch else? Could you give some advice about it?
There are 3 changes from Jinkai.Ma and 1 from me, others is from master.

**Comment by Xylus** [comment]
@jiaqifeng Yup, normally rebase on master (`git rebase master $FEATURE_BRANCH`) would be best, but this PR seems to be targeting the 1.6.x branch.
Are you continuing your work based off of this PR? If not, you can always start a new feature branch off of the current master and throw us a new PR.

**Comment by jiaqifeng** [comment]
@Xylus Oh, I didnot notice this is for 1.6.x branch and I rebased the code for 1.7.x in PR #3538.
So I have to create another branch for 1.6.x. Could I change this PR's branch? Or must I submit another PR?

**Comment by Xylus** [comment]
@jiaqifeng The PR via #3538 should be enough. Thanks!
Closing this - refer to #3538

**Pull request closed without merging**
