### PR TITLE
[#4418] Add Druid Plugin 

### PR DESCRIPTION
**Pull request by VictorZeng**
Title: Druid Plugin Contribution

Link: https://github.com/VictorZeng/pinpoint/tree/druid-plugin/plugins/druid
Target: pinpoint-druid-plugin
Supported Version: All Druid version.
Description: Druid is a database connection pool from Alibaba inc.

ServiceTypes: (6062, "DRUID")
Annotations:
Configurations:
profiler.jdbc.druid=true
profiler.jdbc.druid.connectionclose=true

### CODE REVIEW

**Comment by VictorZeng** [comment]
46201840-bd404400-c347-11e8-8bb1-fcde80428dae

**Comment by VictorZeng** [comment]
46201821-b31e4580-c347-11e8-8397-98ce0598176c

**Comment by VictorZeng** [comment]
@Xylus Can it be merged?

**Comment by Xylus** [comment]
@VictorZeng 
It still says the branch cannot be rebased due to conflicts :(

**Pull request closed without merging**
