### PR TITLE
ElasticsearchBBoss Client Plugin Contribution

### PR DESCRIPTION
**Pull request by yin-bp**
Title: Elasticsearch Client Plugin Contribution

Link: https://github.com/yin-bp/pinpoint/tree/master/plugins/elasticsearch-bboss
Target: Elasticsearch Rest Client BBoss
Supported Version: All Elasticsearch version,BBoss version 5.1.6,pinpoint 1.8.1
Description: This agent plugin is worked with elasticsearch rest client BBoss,BBoss is a best Java Highlevel Rest client for ElasticSearch.

ServiceTypes: [1971, "ElasticsearchBBoss"],[1972, "ElasticsearchBBossEvent"],[9977, "ElasticsearchBBossExecutor"]
Annotations: [971, "es.args"],[972, "es.url"],[973, "es.dsl"],[974, "es.action"],[975, "es.responseHandle"],[976, "es.version"]
Configurations: List of configuration keys and description the plugin adds.

profiler.elasticsearchbboss.enabled=true //enable or disable this plugin, default true.
profiler.elasticsearchbboss.recordResult=false //record or disable record method return value ,default false.
profiler.elasticsearchbboss.recordArgs=true //record or disable record method args,default true.
profiler.elasticsearchbboss.recordDsl=true //record or disable record dsl,default true.
profiler.elasticsearchbboss.recordESVersion=true //record or disable record ES Version infomation,default true.
profiler.elasticsearchbboss.recordResponseHandlerClass=false //record or disable record response handle class ,default false.

### CODE REVIEW

**Comment by yin-bp** [comment]
Hi,@RoySRose:
The commits records could not be processed in PR #4666, and a new PR was created. In the future, git rebase will be used to merge the latest version of the code as you suggest. 
Thanks!

**Comment by RoySRose** [comment]
Hello, @yin-bp 

Can you take a look at the `pom.xml` and try to modify it to use `pinpoint-plugin-bom`.
You can take a look at any other plugins `pom.xml` as a sample.
If you check the format of `pom.xml`, such as arcus or cassandra or mongodb plugins.
I think you will get the point:)

I'm still having some dependency issues.
I will take a deeper look into it after the fix.
I think it will automatically solve my problem.

**Comment by yin-bp** [comment]
> Hello, @yin-bp
> 
> Can you take a look at the `pom.xml` and try to modify it to use `pinpoint-plugin-bom`.
> You can take a look at any other plugins `pom.xml` as a sample.
> If you check the format of `pom.xml`, such as arcus or cassandra or mongodb plugins.
> I think you will get the point:)
> 
> I'm still having some dependency issues.
> I will take a deeper look into it after the fix.
> I think it will automatically solve my problem.

Hi,@RoySRose:
The pom.xml file has been modified according to your suggestion. Please check it.

**Comment by yin-bp** [comment]
Hello,@RoysRose:
 A new PR #4875 was created,Thanks

**Pull request closed without merging**
