### PR TITLE
Mysql docker

### PR DESCRIPTION
**Pull request by dawidmalina**
This pull request depends on https://github.com/naver/pinpoint/pull/1767

To be honest I had issue to make it work with current configuration and failed back to use in memory database for pinpoint web. Anyway it only introduce new docker container with mysql and ability to reconfigure db settings from environments.

### CODE REVIEW

**Comment by nstopkimsk** [comment]
@dawidmalina Is there any reason to use  unofficial mysql docker image?

**Comment by dawidmalina** [comment]
Hmm. No, I can switch to official one. No problem.

**Comment by dawidmalina** [comment]
Done

**Comment by nstopkimsk** [comment]
@dawidmalina thanks.

**Pull request merged**
