### PR TITLE
[#noissue] Add ENDPOINT-Record to TransactionInfo

### PR DESCRIPTION
**Pull request by emeroad**
image

### CODE REVIEW

**Comment by emeroad** [comment]
Related issues : https://github.com/naver/pinpoint/pull/6837

**Comment by yjqg6666** [comment]
image

A new column could also be added, the transactionmetadata api has already returned the endpoint data.

**Comment by yjqg6666** [comment]
@emeroad

**Comment by emeroad** [comment]
@yjqg6666 
good idea
Could  you please send a PR?

**Comment by yjqg6666** [comment]
@emeroad I just sent a PR #6863 for that.

**Pull request merged**
