### PR TITLE
Add batch commands to run the QuickStart in the Windows

### PR DESCRIPTION
**Pull request by barneykim**
Add windows batch command for Pinpoint QuickStart.
Add windows batch commands of HBase 0.98.x  to quickstart/support/hbase-win directory.
Remove duplicated command from quickstart/bin/init-hbase.sh and quickstart/bin/reset-hbase.sh and separated into init-hbase.txt and drop-hbase.txt in quickstart/conf directory.
Add quickstart/README.Win.ko.md for Korean.

### CODE REVIEW

**Comment by emeroad** [comment]
안녕하세요. 저희가 1.0.4 릴리즈 준비중이라. 1.0.4릴리즈 후에 받도록 하겠습니다.

**Comment by barneykim** [comment]
알겠습니다. 릴리즈 기대하겠습니다.

**Comment by koo-taejin** [comment]
I want to merge 59dd791a97aaf74b113183839d428654642050fe commit into pinpoint master. 
and this commit will be included 1.0.4 version.

Could you separate 59dd791a97aaf74b113183839d428654642050fe commit from this pull request. 
and others commits treated like a emeroad would say.

Thank you. :)

**Comment by barneykim** [comment]
Pull Request가 진행되지 않았는데 저의 브랜치를 마스터에 머지한 것이 실수였습니다.
2가지 커밋을 반환했습니다.

**Comment by koo-taejin** [comment]
@barneykim 
628386d  94863bb 이것들은 pull request 제목 변경해서 다시 요청 부탁드립니다.  ^^ 해당 이슈는 닫을께요~

**Pull request closed without merging**
