### PR TITLE
[#4418] Add Druid Plugin

### PR DESCRIPTION
**Pull request by VictorZeng**
Title: Druid Plugin Contribution

Link: https://github.com/VictorZeng/pinpoint/tree/druid-plugin/plugins/druid
Target: pinpoint-druid-plugin
Supported Version: All Druid version.
Description: Druid is a database connection pool from Alibaba inc.

ServiceTypes: (6062, "DRUID")
Annotations:
Configurations:
profiler.jdbc.druid=true
profiler.jdbc.druid.connectionclose=true

### CODE REVIEW

**Comment by VictorZeng** [comment]
druid1

**Comment by VictorZeng** [comment]
druid2

**Comment by VictorZeng** [comment]
@Xylus please review~

**Comment by Xylus** [comment]
@VictorZeng Thank you very much for your contribution :+1:

**Pull request merged**
