### PR TITLE
[#4596] Refactor CXF Plugin

### PR DESCRIPTION
**Pull request by VictorZeng**
Title: Cxf Plugin Contribution

Link: https://github.com/VictorZeng/pinpoint/tree/cxf-plugin/plugins/cxf
Target: pinpoint-cxf-plugin
Supported Version: CXF 3.0.0+.
Description: Upgrade cxf version and refactor cxf plugin.

ServiceTypes: 

-   (9081, "CXF_SERVICE_INVOKER");
-   (9082, "CXF_MESSAGE_SENDER");
-   (9083, "CXF_LOGGING_IN");
-   (9084, "CXF_LOGGING_OUT");

Annotations:

-   (202, "cxf.log.id", AnnotationKeyProperty.VIEW_IN_RECORD_SET);
-   (203, "cxf.address", AnnotationKeyProperty.VIEW_IN_RECORD_SET);
-   (204, "cxf.response.code", AnnotationKeyProperty.VIEW_IN_RECORD_SET);
-   (205, "cxf.encoding", AnnotationKeyProperty.VIEW_IN_RECORD_SET);
-   (206, "cxf.http.method", AnnotationKeyProperty.VIEW_IN_RECORD_SET);
-   (207, "cxf.content.type", AnnotationKeyProperty.VIEW_IN_RECORD_SET);
-   (208, "cxf.headers", AnnotationKeyProperty.VIEW_IN_RECORD_SET);
-   (209, "cxf.messages", AnnotationKeyProperty.VIEW_IN_RECORD_SET);
-   (210, "cxf.payload", AnnotationKeyProperty.VIEW_IN_RECORD_SET);

Configurations:

- profiler.cxf.service.enable=true
- profiler.cxf.logging.enable=true

### CODE REVIEW

**Comment by VictorZeng** [comment]
maybe fix #4596

**Comment by VictorZeng** [comment]
Cxf Server Side
cxf server side

**Comment by VictorZeng** [comment]
Cxf Client Side
cxf client side

**Comment by VictorZeng** [comment]
@Xylus please review～

**Comment by Xylus** [comment]
@VictorZeng 
Thank you for all your recent contributions. We greatly appreciate them :)

Couple questions regarding CXF plugin.
(Keep in mind that I am not entirely familiar with CXF so please feel free to correct me where I'm wrong)

As I understand, you have made both the client and server side of the plugin.
This is great, but there doesn't seem to be any trace propagation going on over RPC.
For example when making HTTP calls to Tomcat, our HTTP client plugin would put pinpoint related values into HTTP header and our Tomcat plugin would then read these values from the header to continue the trace.

Is this something that was omitted intentionally?
Please let me know if the above scenario isn't applicable to CXF and I'm misinformed.

Thanks again!

**Comment by VictorZeng** [comment]
@Xylus Thank you for your reply，as I understand, CXF is Services Framework, like JAX-WS(SOAP) and JAX-RS(RESTFUL), It's not a RPC Framework. That is, CXF must run in the web container(Tomcat/Jetty), So I think no trace propagation is required on CXF.

**Comment by VictorZeng** [comment]
@Xylus And the internal implementation of the CXF Client uses the JDK_HTTPURLCONNECTOR, JDK_HTTPURLCONNECTOR can trace propagation.

**Comment by Xylus** [comment]
@VictorZeng Ah I see, thank you for your explanation. :+1:

**Comment by Xylus** [comment]
@VictorZeng 
Just tested out using the cxf sample - https://github.com/apache/cxf/tree/master/distribution/src/main/release/samples/java_first_jaxws and seems to work great.
Thank you for all your recent contributions.

**Comment by VictorZeng** [comment]
@Xylus That's my duty, Thank U.

**Pull request merged**
