### PR TITLE
add traceId search button

### PR DESCRIPTION
**Pull request by linxiaoJVM**
at my project, use MDC feature of log4j and traceId output to log file, the log file store in Elasticsearch, below:

qq 20181024150053

I need search by traceId at pinpoint web, so add a search button at web main html. below:

qq 20181024150524

### CODE REVIEW

**Comment by wangwei0537** [comment]
2018-09-06 12:34:49,084 [INFO] [catalina-exec-101] [XXXXXXXServiceImpl. Java: 58] - [TxId:, SpanId:] xxxxLog is exist.

TxId: SpanId: unreachable

Is it convenient to answer why TxId and SpanId are not valued

**Comment by linxiaoJVM** [comment]
> 2018-09-06 12:34:49,084 [INFO] [catalina-exec-101] [XXXXXXXServiceImpl. Java: 58] - [TxId:, SpanId:] xxxxLog is exist.
> 
> TxId: SpanId: unreachable
> 
> Is it convenient to answer why TxId and SpanId are not valued

at pinpoint.config file, the log4j value default is false , change the value to true
# log4j (guide url : https://github.com/naver/pinpoint/blob/master/doc/per-request_feature_guide.md)
###########################################################
profiler.log4j.logging.transactioninfo=false

**Comment by wangwei0537** [comment]
> > 2018-09-06 12:34:49,084 [INFO] [catalina-exec-101] [XXXXXXXServiceImpl. Java: 58] - [TxId:, SpanId:] xxxxLog is exist.
> > TxId: SpanId: unreachable
> > Is it convenient to answer why TxId and SpanId are not valued
> 
> at pinpoint.config file, the log4j value default is false , change the value to true
> # log4j (guide url : https://github.com/naver/pinpoint/blob/master/doc/per-request_feature_guide.md)
> 
> ###########################################################
> profiler.log4j.logging.transactioninfo=false

thanks

**Comment by miaowang1** [comment]
thank you

**Comment by dinesh4747** [comment]
@linxiaoJVM - when we can expect this release ?

**Comment by yjqg6666** [comment]
How about update for UI v2?

**Comment by linxiaoJVM** [comment]
> 
> 
> @linxiaoJVM - when we can expect this release ?

waiting for merge to master

**Comment by linxiaoJVM** [comment]
> 
> 
> How about update for UI v2?

I don't understand what you mean

**Comment by yjqg6666** [comment]
> > How about update for UI v2?
> 
> I don't understand what you mean

Add the traceId search button to UI version 2(the default UI for pinpoint version 2.x), you may check https://github.com/naver/pinpoint/blob/master/doc/ui_guide.md to enable the v2 version for 1.8.x and [the live demo ](http://125.209.240.10:10123/v2/main/ApiGateway@SPRING_BOOT/5m/2020-03-09-09-07-34?inbound=1&outbound=4&wasOnly=false&bidirectional=false)

**Comment by SRE-maker** [comment]
When this feature of trace id search button will be released @linxiaoJVM @emeroad

**Comment by yjqg6666** [comment]
@linxiaoJVM  ignore me.  From the PR the screenshot you provided is UI version 1.  From the code i might consider that the web UI V2 is supported.  Just wait for the final release.

**Comment by linxiaoJVM** [comment]
> 
> 
> When this feature of trace id search button will be released @linxiaoJVM @emeroad

 wait for the release

**Comment by emeroad** [comment]
Resolved : #6774

**Comment by dinesh4747** [comment]
@emeroad - Awesome news!!! when this feature will be available, can we expect in next release ?

**Pull request closed without merging**
