### PR TITLE
Enable Elasticsearch bboss plugin to fix bug #6048

### PR DESCRIPTION
**Pull request by yin-bp**
2.Enable  Elasticsearch bboss plugin to fix bug #6048

### CODE REVIEW

**Comment by RoySRose** [comment]
Hello, @yin-bp 

I don't think `log4j.xml` is necessary here. What do you think?

**Comment by yin-bp** [comment]
@RoySRose 
There are some log4j warn when run elasticsearch bboss integration test,so I think here need a log4j.xml file:
```
log4j:WARN No appenders could be found for logger (org.eclipse.aether.internal.impl.DefaultLocalRepositoryProvider).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

**Comment by RoySRose** [comment]
Hello, @yin-bp 

Great~!
As usual. can you merge the commits into one instead of two?
since the first commit includes log4j and the second one just removes it again.

**Comment by yin-bp** [comment]
for squashed  and merge commits

**Pull request closed without merging**
