### PR TITLE
Suppport log4j2 1.9

### PR DESCRIPTION
**Pull request by licoco**

### CODE REVIEW

**Comment by licoco** [comment]
@minwoo-jung

**Comment by licoco** [comment]
@Xylus Check the code

**Comment by licoco** [comment]
> I'm sorry about answering late.
> 
> Two constractor methods are not present in all versions. Exception handling is required.
> 
> Where is log4j2IT test? please ref log4IT?

constractor methods   Log4jPlugin.java  109 lines 
 InstrumentMethod constructor = InstrumentUtils.findConstructor(target, parameterTypes);
if (constructor == null) {

Is that not possible? ？？？
>

**Comment by minwoo-jung** [comment]
@licoco
Great!
I was mistaken.
I did not see the contents of the addInterceptor method.

In addition, could you add more annotations on the existence of the constructor method depending on the version? It will be helpful for developers to understand.

**Comment by licoco** [comment]
> @licoco
> Great!
> I was mistaken.
> I did not see the contents of the addInterceptor method.
> 
> In addition, could you add more annotations on the existence of the constructor method depending on the version? It will be helpful for developers to understand.

It is OK now

**Comment by licoco** [comment]
@minwoo-jung 
is it ok?

**Comment by minwoo-jung** [comment]
did you see 2.11.0 version?

There is not code for this constructor method.
```
    private Log4jLogEvent(String loggerName, Marker marker, String loggerFQCN, Level level, Message message, Throwable thrown, ThrowableProxy thrownProxy, StringMap contextData, ContextStack contextStack, long threadId, String threadName, int threadPriority, StackTraceElement source, long nanoTime) {
        this.instant = new MutableInstant();
        this.endOfBatch = false;
        this.loggerName = loggerName;
        this.marker = marker;
        this.loggerFqcn = loggerFQCN;
        this.level = level == null ? Level.OFF : level;
        this.message = message;
        this.thrown = thrown;
        this.thrownProxy = thrownProxy;
        this.contextData = contextData == null ? ContextDataFactory.createContextData() : contextData;
        this.contextStack = (ContextStack)(contextStack == null ? ThreadContext.EMPTY_STACK : contextStack);
        this.threadId = threadId;
        this.threadName = threadName;
        this.threadPriority = threadPriority;
        this.source = source;
        if (message instanceof LoggerNameAwareMessage) {
            ((LoggerNameAwareMessage)message).setLoggerName(loggerName);
        }

        this.nanoTime = nanoTime;
    }
```

And please check my cmment for your code. 
```


It is perfect!

I will give minor advice.
The variable name need to is changed threadContextClass

I recommend git commend rebase --interactive and squash to combine multiple commits into one.
Please ref this link
```

**Comment by licoco** [comment]
> link

I see 2.10... Wait till I see the latest version.

**Comment by licoco** [comment]
> did you see 2.11.0 version?
> 
> There is not code for this constructor method.
> 
> ```
>     private Log4jLogEvent(String loggerName, Marker marker, String loggerFQCN, Level level, Message message, Throwable thrown, ThrowableProxy thrownProxy, StringMap contextData, ContextStack contextStack, long threadId, String threadName, int threadPriority, StackTraceElement source, long nanoTime) {
>         this.instant = new MutableInstant();
>         this.endOfBatch = false;
>         this.loggerName = loggerName;
>         this.marker = marker;
>         this.loggerFqcn = loggerFQCN;
>         this.level = level == null ? Level.OFF : level;
>         this.message = message;
>         this.thrown = thrown;
>         this.thrownProxy = thrownProxy;
>         this.contextData = contextData == null ? ContextDataFactory.createContextData() : contextData;
>         this.contextStack = (ContextStack)(contextStack == null ? ThreadContext.EMPTY_STACK : contextStack);
>         this.threadId = threadId;
>         this.threadName = threadName;
>         this.threadPriority = threadPriority;
>         this.source = source;
>         if (message instanceof LoggerNameAwareMessage) {
>             ((LoggerNameAwareMessage)message).setLoggerName(loggerName);
>         }
> 
>         this.nanoTime = nanoTime;
>     }
> ```
> And please check my cmment for your code.
> 
> ```
> 
> 
> It is perfect!
> 
> I will give minor advice.
> The variable name need to is changed threadContextClass
> 
> I recommend git commend rebase --interactive and squash to combine multiple commits into one.
> Please ref this link
> ```

Let me adjust the interception structure

**Comment by licoco** [comment]
https://github.com/naver/pinpoint/pull/5402

**Pull request closed without merging**
