### PR TITLE
Add Spring Boot support

### PR DESCRIPTION
**Pull request by Xylus**
#951 Add plugin for detecting Spring Boot applications, and related icons to Pinpoint web.

### CODE REVIEW

**Comment by rajc** [comment]
do you have an example of how one would use pin point agent with spring boot?

i am trying: java -jar repoc_house_fetch-0.0.1-SNAPSHOT.jar -javaagent:/home/raj/Downloads/pinpoint-agent-1.5.2/pinpoint-bootstrap-1.5.1.jar -Dpinpoint.agentId=home-agent -Dpinpoint.applicationName=homeapp

but its not working.

**Comment by Xylus** [comment]
Hi rajc,

`-jar $JAR_PATH` should come after the property options:
```
java -javaagent:/home/raj/Downloads/pinpoint-agent-1.5.2/pinpoint-bootstrap-1.5.1.jar -Dpinpoint.agentId=home-agent -Dpinpoint.applicationName=homeapp -jar repoc_house_fetch-0.0.1-SNAPSHOT.jar
```

Let me know if it still doesn't work.

**Comment by rajc** [comment]
thank you!! i mised that part.

i am on local network.  i have a home server and all of the below are on that same server.
the server ip is 192.168.1.11.


i have start the following docker image: https://hub.docker.com/r/yous/pinpoint/

like this: sudo docker run -i -t -p 28080-28082:28080-28082 -p 49994:9994 -p 49995:9995/udp -p 49996:9996/udp --cap-add SYS_PTRACE yous/pinpoint:1.5.1 bash

i can get the test app running however when i try to boot strap my app with this command
java -javaagent:/home/raj/Downloads/pinpoint-agent-1.5.2/pinpoint-bootstrap-1.5.1.jar -Dpinpoint.agentId=home-agent -Dpinpoint.applicationName=homeapp -jar repoc_house_fetch-0.0.1-SNAPSHOT.jar

with these changes to the config file for the port 
----------------------------------------------
profiler.collector.ip=192.168.1.11

# placeHolder support "${key}"
profiler.collector.span.ip=${profiler.collector.ip}
profiler.collector.span.port=49996

# placeHolder support "${key}"
profiler.collector.stat.ip=${profiler.collector.ip}
profiler.collector.stat.port=49995

# placeHolder support "${key}"
profiler.collector.tcp.ip=${profiler.collector.ip}
profiler.collector.tcp.port=49994

i keep getting this errors:

2016-04-18 21:16:31 [WARN ](c.n.p.r.c.PinpointClientFactory$ConnectEvent:343) try reconnect. connectAddress:/192.168.1.11:49994
2016-04-18 21:16:31 [INFO ](c.n.p.r.c.DefaultPinpointClientHandler:196) DefaultPinpointClientHandler@2ff3b54e initReconnect() started.
2016-04-18 21:16:31 [DEBUG](c.n.p.r.c.PinpointClientHandlerState:118) DefaultPinpointClientHandler@2ff3b54e stateTo() started. to:BEING_CONNECT
2016-04-18 21:16:31 [INFO ](c.n.p.r.c.PinpointClientHandlerState:125) DefaultPinpointClientHandler@2ff3b54e stateTo() completed. Socket state change success(updateWanted:BEING_CONNECT ,before:NONE ,current:BEING_CONNECT).
2016-04-18 21:16:31 [INFO ](c.n.p.r.c.DefaultPinpointClientHandler:203) DefaultPinpointClientHandler@2ff3b54e initReconnect() completed.
2016-04-18 21:16:31 [DEBUG](c.n.p.r.c.DefaultPinpointClientHandler:144) DefaultPinpointClientHandler@2ff3b54e channelOpen() started. channel:[id: 0x70a039a5]
2016-04-18 21:16:31 [INFO ](c.n.p.r.c.DefaultPinpointClientHandler:556) DefaultPinpointClientHandler@2ff3b54e channelClosed() started.
2016-04-18 21:16:31 [DEBUG](c.n.p.r.c.PinpointClientHandlerState:118) DefaultPinpointClientHandler@2ff3b54e stateTo() started. to:CONNECT_FAILED
2016-04-18 21:16:31 [INFO ](c.n.p.r.c.DefaultPinpointClientHandler:460) DefaultPinpointClientHandler@2ff3b54e exceptionCaught() occurred. state:BEING_CONNECT, caused:Connection refused: /192.168.1.11:49994.
2016-04-18 21:16:31 [INFO ](c.n.p.r.c.PinpointClientHandlerState:125) DefaultPinpointClientHandler@2ff3b54e stateTo() completed. Socket state change success(updateWanted:CONNECT_FAILED ,before:BEING_CONNECT ,current:CONNECT_FAILED).
2016-04-18 21:16:31 [DEBUG](c.n.p.r.c.DefaultPinpointClientHandler:519) DefaultPinpointClientHandler@2ff3b54e closeResources() started.
2016-04-18 21:16:31 [INFO ](c.n.p.r.c.PinpointClientHandshaker :238) PinpointClientHandshaker@53eafcce handshakeAbort() started.
2016-04-18 21:16:31 [INFO ](c.n.p.r.c.PinpointClientHandshaker :242) PinpointClientHandshaker@53eafcce unexpected state
2016-04-18 21:16:31 [DEBUG](c.n.p.r.c.RequestManager           :164) close()



any idea what could be wrong?

**Comment by TimeStarRipple** [comment]
Hello, Xylus
I want to know that where is input the "profiler.collector.ip"

**Comment by Xylus** [comment]
Hi @TimeStarRipple 
It's in the *pinpoint.config* file under $PINPOINT_AGENT directory. [Here](https://github.com/naver/pinpoint/blob/master/doc/installation.md#configuration-2)'s a more detailed installation guide.

**Comment by TimeStarRipple** [comment]
Thanks, 
I know what your mean. Now, I have a question, I don't know the agent's ports should be exposed when I write a dockerfile

**Comment by TimeStarRipple** [comment]
Hi, Xylus
I have solved my problem. But now, I meet a problem. I can see my agent in the web, but it has no data show in the web.
Thank you very much.

**Comment by Xylus** [comment]
@TimeStarRipple 
Could you open up a new issue for this? It'd be good to include some logs (agent, collector, web) as well, and some description of your environment.
Thanks

**Comment by TimeStarRipple** [comment]
@Xylus 
Hello, Xylus,thank you for you help
I have solved my problem. Because I did not open udp port, I met this problem.
But now, I meet another problem, The CPU data did not show. The following is my environment configuration.
tomcat 8.0.32
collector, web 1.6.0-RC2
agent 1.6.0
jdk java-8-openjdk

The following is my error screenshots.
[bug1](https://github.com/TimeStarRipple/note/blob/master/%E5%88%86%E5%B8%83%E5%BC%8F/images/bug1.png)
[bug2](https://github.com/TimeStarRipple/note/blob/master/%E5%88%86%E5%B8%83%E5%BC%8F/images/bug2.png)

**Comment by Xylus** [comment]
@TimeStarRipple 
Please create a new issue for the CPU data collection issue!

**Comment by TimeStarRipple** [comment]
@Xylus 
I'm sorry caused you trouble, I have just create a new issue. The CPU data did not show #2330

**Pull request merged**
