### PR TITLE
Add support for Weblogic Plugin

### PR DESCRIPTION
**Pull request by andyspan**
Weblogic Plugin Contribution
Link: [/plugins/weblogic](https://github.com/andyspan/pinpoint/tree/master/plugins/weblogic)
Target: pinpoint-weblogic-plugin-1.6.2-SNAPSHOT.jar
Supported Version: weblogic 10.* and weblogic 12.*

ServiceTypes: WEBLOGIC =1989,WEBLOGIC _METHOD=1992
Annotations:
Configurations:
profiler.weblogic.enable=
profiler.weblogic.bootstrap.main=
profiler.weblogic.excludeurl=

The plugin is verified on 12c and 10.3.6

Example：
topo

calltree

### CODE REVIEW

**Comment by Xylus** [comment]
Hi @andyspan
Thanks for your contribution.

We're planning to target the merge for 1.6.2-SNAPSHOT as 1.6.1 release is almost ready and we don't want to introduce anything major into it.
Please hang on tight for a bit longer!

Meanwhile, if you could keep the code updated with master (via rebase) once in a while, that would be great.
Thanks!

**Comment by andyspan** [comment]
@Xylus It's my pleasure.

**Comment by jacarrichan** [comment]
I  do not think  this plugin  need   com.oracle.weblogic.weblogic.  
We can use javax.servlet.servlet-api to replace weblogic.jar 

```	
	<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>servlet-api</artifactId>
			<version>2.5</version>
			<scope>provided</scope>
		</dependency>

```

**Comment by jacarrichan** [comment]
need  WEBLOGIC.png    at   pinpoint/web/src/main/webapp/images/icons/

**Comment by andyspan** [comment]
~

**Comment by emeroad** [comment]
Sorry. We will merge in 1.7.1

**Comment by jacarrichan** [comment]
may be we  should  add README file    for  how to config weblogic.

**Comment by andyspan** [comment]
Thanks for your reminder, it has been updated. @jacarrichan

**Comment by jacobsy** [comment]
when merge the feature？

**Comment by jacobsy** [comment]
when merge the feature？ @Xylus

**Comment by Xylus** [comment]
Hi @jacobsy 
Thanks for the reminder, don't think it'll be ready for 1.7.2 (which should be very soon) so will target it for 1.7.3 release.

**Comment by jaehong-kim** [comment]
@andyspan 

Rebase and update for pinpoint-1.8.0-SNAPSHOT.
Please review.
#3963

**Comment by andyspan** [comment]
Thank you very much，but I'm afraid there will be some problems，Plug-in based on javax.servlet-api.jar will cause the pinpoint to throw an error under weblogic 10.3.1 or older version . It's been too long, I can't remember it very clearly.
If you can test this plug-in under weblogic 10.3.1 , I will be  greatly appreciated.

**Comment by jaehong-kim** [comment]
@andyspan 
I was not able to test weblogic 10.3.1 for other problems.
Modified the Oracle servlet class to be used internally only.
Please review.
#3983

**Comment by jaehong-kim** [comment]
Thank you for your contribution.

**Comment by Rnic** [comment]
@andyspan hi ，i'm tring to use your weblogic plugin and find some problems.

1.  i'm adding the plugin  'pinpoint-weblogic-plugin-1.8.0-SNAPSHOT.jar' into  the  /weblog12/bea/user_projects/Dockerdomain/plugin  dir

2.  i  had changed the 'pinpoint.config'  and  add these parmeters
profiler.weblogic.enable = true
profiler.weblogic.bootstrap.main = weblogic.Server
profiler.weblogic.excludeurl = /aa/test.html, /bb/exclude.html

3. i added agent parmeters in StartWeglogic.sh 

SAVE_JAVA_OPTIONS="${JAVA_OPTIONS}-javaagent:/weblog12/bea/user_projects/Dockerdomain/pinpoint-bootstrap-1.7.1.jar -Dpinpoint.agentId=pp27001  -Dpinpoint.applicationName=WeblogicTest1"
   

did i need do anything else ?   when i see the dashboard, i just can see the application 'WeblogicTest1' in the application list ,meanwhile i can't see anyother monitor things .

**Comment by andyspan** [comment]
The problem may be due to inconsistent data，Had you put the plug-in into the collector and pinpoint website?  Meanwhile，your website may lack a weblogic image.

**Comment by Rnic** [comment]
@andyspan  oh,that's a great solution! thanks for your help!!!

**Comment by Rnic** [comment]
@andyspan  hi，I'm sorry to disturb you again， i what to konw why these Services show me 'N/A'  in a weblogic application(12c version),but in a tomcat application , i can see some jars in it which i am quoting in my own application program.


ddd

**Comment by andyspan** [comment]
@Rnic  there is something wrong with the ServiceType， your serviceType is ‘’STAND_ALONE‘’.Normally，It should be displayed as WEBLOGIC . it is better to check the log of pinpoint agent.

**Comment by xttyawei** [comment]
@jacobsy  @andyspan @Rnic @jaehong-kim 
so everyone，
 in which pinpoint version，can I use weblogic plugin?  Is this plugin available in pinpoint 1.6.2?  
thank you

**Comment by Rnic** [comment]
@xttyawei  hi, i used pinpoint 1.7.2 , that plugin can be used in webloigc. 
i didn't use 1.6.2 yet.

**Pull request closed without merging**
