### PR TITLE
Add script to install maven project and build all docker images

### PR DESCRIPTION
**Pull request by marcoblos**
It is necessary to run _docker-compose up_ without run command per command manually.

### CODE REVIEW

**Comment by koo-taejin** [comment]
Hi marcoblos 

Building and Installing with scripts is a really good idea.

But there are a lot of things to consider.
1. whether maven executable file contains PATH environment variable
2. If not, whether MAVEN_HOME environment variable is set
3. If not, show enough error log 

In addition, 
It would be better to separate the docker image creation using additional parameter.
Because, creating docker image is very heavy, and can execute in specific situation. 

So, we can't merge this pull request. 

thanks.

**Comment by marcoblos** [comment]
@ Koo-taejin Thanks for your reply. I will improve this feature.

In my personal repository I do it better, download maven, jdk and everything to make this work, but I think if I do all those things, the script would be very slow.

Do you have more ideias to improve this script?

I will think better about this script.

Thanks in advance.

**Comment by koo-taejin** [comment]
@marcoblos 

I need more worries about related build a docker container.
I think it would be nice to include only the project build at now.

The following is a simple idea.
```
// usage
./install.sh -P{profile dev|release}

# check JAVA_6_HOME

# check JAVA_7_HOME

# check JAVA_8_HOME

# To check if Maven has been installed

# To check installed maven version higher than 3.2.x+

mvn clean install -Dmaven.test.skip=true -P{profile}
```

**Comment by marcoblos** [comment]
Can you share your worries about build a docker images? There is a problem about pinpoint with docker?

Thanks @koo-taejin

**Comment by koo-taejin** [comment]
If running this script in my development environment will fail.

It is not a good idea to make it executable only under certain circumstances where you can connect to the docker container with a generic name of install.sh.
If so, the default install.sh file is a simple project build that can be run in any environment, and building the docker image is optional.

In this case, you should try to figure out what the option name will do and if there are any additional options to extract.

**Pull request closed without merging**
