### PR TITLE
Add kafka plugin

### PR DESCRIPTION
**Pull request by lopiter**
Title: Kafka Plugin Contribution

Link: https://github.com/lopiter/pinpoint/tree/add-kafka-plugin
Target: Kafka
Supported Version: 0.11.0.1
Description: https://kafka.apache.org

this plugin use kafka header(not support lower version)
not support async(use tracecontext in ThreadLocal)
this plugin add pinpoint trace data to kafka message value(include tid , spanid ..)
kafka consumer must remove pinpoint value from message and create monitoring data
please check this code ( https://github.com/lopiter/pinpoint/blob/add-openwhisk-plugin/plugins/openwhisk/src/main/java/com/navercorp/pinpoint/plugin/openwhisk/aspect/InvokeReactiveAspect.java)
ServiceTypes: KAFKA
Configurations:

profiler.kafka.enable : set enable/disable plugin
profiler.kafka.caller : set caller that send message using kafka name

### CODE REVIEW

**Comment by koo-taejin** [comment]
please insert clover.license file to plugin home directory.
(You can copy and use the clover.license file.)

**Comment by koo-taejin** [comment]
Really appreciate your contribution.
			
But I think this kafka plugin seems to be for openwhisk.
In conclusion, Consumer side code needs improvement.

Here's why:
1. If the application uses kafka alone, the remote trace is not possible with the plugin.
2. Has riskt when using type change In the ConsumerRecordAspect
```
    byte [] valueIncludePinpointHeader = new byte [pinpointHeader.length + ((byte []) __value (). length];
    System.arraycopy (pinpointHeader, 0, valueIncludePinpointHeader, 0, pinpointHeader.length);
    System.arraycopy (__value (), 0, valueIncludePinpointHeader, pinpointHeader.length, ((byte []) __value ()).
    return (V) valueIncludePinpointHeader;
```

Please consider it.

thanks.

**Comment by lopiter** [comment]
I changed my code to resolve below two opinion

1. If the application uses kafka alone, the remote trace is not possible with the plugin.
   If plugin user set profiler.kafka.create.context config value to true, it create monitoring data in ConsumerRecord's constructor like below

image

2. Has risk when using type change In the ConsumerRecordAspect
This plugin provide a chance to other user can extend this plugin.
User type encoder class like below, plugin use this class when add pinpoint information to ConsumerRecord value
```
profiler.kafka.include.encoder=com.navercorp.pinpoint.plugin.kafka.encoder.BytesEncoder
```
please check this code (https://github.com/lopiter/pinpoint/blob/add-kafka-plugin/plugins/kafka/src/main/java/com/navercorp/pinpoint/plugin/kafka/encoder/PinpointValueEncoder.java)

I don't know exactly other user need this feature. if you think this feature is not necessary to other user, then I can move this feature to openwhisk plugin

thanks your reply

**Comment by junoyoon** [comment]
@koo-taejin any comment?

**Comment by koo-taejin** [comment]
@junoyoon I will check the issue after 1.7.2 is released.

**Comment by dinesh4747** [comment]
@koo-taejin - Can we expect Kafka plugin by next version - 1.8.0 ?

**Comment by koo-taejin** [comment]
@dinesh4747 
I am reviewing it for how can make it better.
However, I can not guarantee that use in 1.8.0.

**Comment by koo-taejin** [comment]
@lopiter 


Thank you very much for your contribution.
However, I want to change some things in you're pull request.

1. Changing the value seems very dangerous. (It is recommended to use header.)
2. It seems that doing Remote Trace when creating ConsumerRecord is not suitable for kafka's method nature.
(kafka only support poll multiple ConsumerRecords. using `ConsumerRecords<K, V> poll(long timeout)`)
3. It would be nice if you could show more information than now.
(like the rabbitmq plugin, ex. topic, partition, offset, remoteAddress etc..)
4. It would be nice if you could show kafka node in server map.

I modified you're pull request to improve as I thought.
There is a bit more to fix, but I think You can refer to it.
https://github.com/koo-taejin/pinpoint/tree/%23kafka_plugin

* branch server-map
default

* branch callstack
default

**Comment by lopiter** [comment]
@koo-taejin 
wow it's look so great, a specialist is different.^^
i really appreciate it.

**Comment by wh0511** [comment]
@koo-taejin Hi koo-taejin, I have a question for you to help with.I downloaded the code from this link https://github.com/koo-taejin/pinpoint/tree/%23kafka_plugin.I wrote a demo for kafka,but  can't get information about the kafka,So I think there's a problem with my demo.Can you send me your demo link? Can I learn it?Thank you very much!

**Comment by wh0511** [comment]
@koo-taejin this link https://github.com/koo-taejin/pinpoint/tree/%23kafka_plugin  This is the link you provided.

**Comment by wh0511** [comment]
Hi,@lopiter,this version 
<groupId>org.apache.kafka</groupId>
            <artifactId>kafka_2.12</artifactId>
            <version>1.1.0</version>
Can you share your demo with me? Thank you very much

**Comment by koo-taejin** [comment]
hi @wh0511 

I need more information to solve your problem.

For the kafka plugin, you have to rebuild the collector, the web, and so on.
please post more detail about the environment and how to use it and so on.

thanks.

**Comment by wh0511** [comment]
@koo-taejin hello specialist.I uploaded my demo to github.this link https://github.com/wh0511/springclud-feign-kafka  .The model uses springclud,feign,kafka.Distributed through feign. Let me describe my operation.
1.Download the version provided in your link(include kafka plugin).
2.Modifying the configuration file has reached the purpose of connecting local resources.(Like connecting to the hbase)
3.Packaging the pinpoint project.
4.start collector.
5.start eureka-server use the following command java -javaagent:F:\github-project\pinpoint--kafka_plugin\pinpoint--kafka_plugin\agent\target\pinpoint-agent-1.7.2-SNAPSHOT\pinpoint-bootstrap-1.7.2-SNAPSHOT.jar -Dperftrace.agentId=eureka-server -Dperftrace.applicationName=eureka-server -jar eureka-server-1.0-SNAPSHOT.jar
6.start feign-consumer use the following command java -javaagent:F:\github-project\pinpoint--kafka_plugin\pinpoint--kafka_plugin\agent\target\pinpoint-agent-1.7.2-SNAPSHOT\pinpoint-bootstrap-1.7.2-SNAPSHOT.jar -Dperftrace.agentId=feign-consumer  -Dperftrace.applicationName=feign-consumer  -jar eureka-server-1.0-SNAPSHOT.jar
7.start kafka use the following command java -javaagent:F:\github-project\pinpoint--kafka_plugin\pinpoint--kafka_plugin\agent\target\pinpoint-agent-1.7.2-SNAPSHOT\pinpoint-bootstrap-1.7.2-SNAPSHOT.jar -Dperftrace.agentId=kafka-provider -Dperftrace.applicationName=kafka-provider -jar eureka-server-1.0-SNAPSHOT.jar
8.strat kafkaconsumer  use the following command java -javaagent:F:\github-project\pinpoint--kafka_plugin\pinpoint--kafka_plugin\agent\target\pinpoint-agent-1.7.2-SNAPSHOT\pinpoint-bootstrap-1.7.2-SNAPSHOT.jar -Dperftrace.agentId=kafka-consumer -Dperftrace.applicationName=kafka-consumer -jar eureka-server-1.0-SNAPSHOT.jar
9.Browser address bar input http://localhost:3035/kafka?msg=abcdef kafkaconsumer's console can received news like this " msg's value :0
offset = 20679, key = 0, value = 0"
10.We can also refresh several times to send more messages.

**Comment by wh0511** [comment]
@koo-taejin  I forgot to say thank you.Thanks again for your help.

**Comment by wh0511** [comment]
@koo-taejin If my model has a problem, or if you are inconvenient to see, can you provide your model for me to learn?Thank you anyway.

**Comment by koo-taejin** [comment]
@wh0511 
I wonder how each of your applications shown in pinpoint web.
and I also wonder about kafka related settings in pinpoint.config.

thanks.

**Comment by wh0511** [comment]
@koo-taejin 
Hello experts!
I can get the topology diagram.
image
But you can see it.My customers didn't connect, so to ask you, how do consumers receive can get. I am in accordance with the interceptors to intercept method to obtain, but didn't want the result

**Comment by koo-taejin** [comment]
@wh0511 
Kafka does not have api to handle each ConsumerRecord.
Therefore, you must set target that handles ConsumerRecord for remote trace

To trace your consumer you must include the following settings:
ex) profiler.kafka.entryPoint=clazzName.methodName

**Comment by koo-taejin** [comment]
@wh0511 
I'm very glad to hear that. :)

**Comment by lawrencewu** [comment]
To trace consumer,  you must include the following settings, profiler.kafka.entryPoint=clazzName.methodName, if this do, it's not **Universal，**  you have to config this for every project manually,  Is there any enhancement for this plugin to interceptor the ConsumerRecord ?

**Comment by koo-taejin** [comment]
hi @lawrencewu 

I know it's not universal.
I had a lot of worries and decided that this was the best choice.
It is difficult to apply kafka like previous plugins.

If  were to target the constructor to the interceptor, there were some issues.
Value type is not fixed, and difficult to do Remote Trace like the above image.

I think it would be great if I could use a more convenient kafka plugin.
If you have a better solution, please feel free to post you're opinion .

thanks.

**Comment by lawrencewu** [comment]
@koo-taejin Thanks for your reply. I'm seeking for a better solution, how about make plugin on framework "spring-kafka" ?

**Comment by wh0511** [comment]
Hi @koo-taejin,Check out kafka's source code in detail in recent days.I found that the client sent only the following attributes to the server in general,topic,headers,key,value,partition. So, if we want to develop a version of kafka that is less than 0.11,We can only customize development,Specifically, it refers to some of the basic information of the target application(such as : topic,key,value), which can be added to the pinpoint information according to our customization.All of this is because there is no "headers" attribute in the lower kafka version.Expert, don't know what I understand, right?Thank you for your help all the time!

**Comment by koo-taejin** [comment]
hi @wh0511 
Yes, I know in the lower version that Kafka has no header property. 

Currently, I am planning to only support version that supports header. 
It takes too much effort to manage all versions.

In addition, if I support version which without header, then must define something producer and consumer in advance, which is very risky.

I hope you understand this decision.

thanks.

**Comment by koo-taejin** [comment]
@lawrencewu 
I will look at spring-kafka.
thanks :)

**Comment by wh0511** [comment]
@koo-taejin ,Thank you very much, expert!

**Comment by lawrencewu** [comment]
@koo-taejin  Is there any progress? The same issue for "Spring-kafka" framework when deal with generic type in 

```
public interface GenericMessageListener<T> extends KafkaDataListener<T> {
    void onMessage(T var1);
}
```

I use a class to inherit the MessageListner,

```
public class CustomizeMessageListener implements MessageListener<String, String> {
    @Override
    public void onMessage(ConsumerRecord<String, String> record) {

    }
}

```
then extends this **CustomizeMessageListener** class, but this does not work, **MessageListener** is invoked async.

**Comment by koo-taejin** [comment]
@lawrencewu 
I am sorry for late answer 

I want to look at spring-kafka, but  I'm doing other things right now.
If you analyze spring-kafka and create plugin.I think it will be great. 

I think it is not a problem if the listener is execute as Async. because ConsumerRecord has a Headers.
(This is my opinion and if I look deeply, this opinion can be wrong.)

thanks.

**Comment by lawrencewu** [comment]
@koo-taejin  thanks for your reply. at last, it works. 
```
public  abstract class CustomizeMessageListener implements MessageListener<String, String> {
   
    public void onMessage(ConsumerRecord<String, String> record) {
                onComplete(record);
    }

   public abstract void onComplete(ConsumerRecord<String, String> record);
}
```

in the biz application

public void ExtendsClass extends CustomizeMessageListener{
    
    @Override
    public void onComplete(ConsumerRecord<String, String> record){
     }
}

and then let the interceptor to intercept the **onMessage** method, it works.

**Comment by koo-taejin** [comment]
@lawrencewu 
I am glad that you can do whatever you want.
I will look at spring-kafka.

thanks :)

**Comment by koo-taejin** [comment]
pull request is merged via #4461

**Comment by lawrencewu** [comment]
@koo-taejin   PR #4461 needs special method to deal with `ConsumerRecords<K, V> poll(long timeout)`

**Comment by koo-taejin** [comment]
@lawrencewu 
Pinpoint now support spring-kafka. (#4939)
Please try it out and tell us if you have any feedback. 
thanks.

**Pull request closed without merging**
