### PR TITLE
* Modify some resource paths

### PR DESCRIPTION
**Pull request by f1194361820**
* Modify some resource paths

### CODE REVIEW

**Comment by nstopkimsk** [comment]
@denzels  please review this pr.

**Comment by denzelsN** [comment]
You had to modify the source code as follows:

sImageDir": './images/' ==>  .sImageDir": 'images/'

and use as follows: 

sImageDir.substring(1)  ( == "mages/"  )

I think the code is being mixed.

**Comment by f1194361820** [comment]
in runtime, the value of  sImageDir  is "/images"

**Comment by denzelsN** [comment]
sorry. I was mistaken.
You must modify sImageDir of serverMap.js.

**Pull request closed without merging**
