### PR TITLE
Adds trace support for Postgresql jdbc driver 9.4.1207+

### LINKED ISSUE #2239: Add trace support for Postgresql jdbc driver 9.4.1207+
Looks like there was a major overhaul in postgresql jdbc driver code in 9.4.1207.
Postgresql plugin needs to support this change.

If anyone's willing to work on this this, please feel free to leave a message here.

related issue - #2157

### PR DESCRIPTION
**Pull request by Xylus**
Also fixes some issues with the plugin for other postgresql jdbc driver versions

resolves #2239

### CODE REVIEW

**Comment by ofauchon** [comment]
Hi,
I need this fix. Are there master nightly build  ? 
Or I need to build it by myself ?

Thanks 
Olivier

**Comment by Xylus** [comment]
@ofauchon 
There isn't a separate build for the master branch, so you'll have to clone and build it.
Feel free to open up a new issue if anything doesn't work if you decide to try it out.
Thanks!

**Comment by ofauchon** [comment]
Can I use a fresh build for the agent, and mainstream 1.6.2 server build ? 
Or I need to upgrade both server & agents ?

**Comment by Xylus** [comment]
@ofauchon With the current master code, it should work, but I can't guarantee it.
Connecting a lower version agent to a higher version collector works, but the other way around is not always guaranteed.

**Pull request merged**
