### PR TITLE
fix esc to clear search txId input box

### PR DESCRIPTION
**Pull request by yjqg6666**
Fix press escape key won't clear the search box.

### CODE REVIEW

**Comment by yjqg6666** [comment]
@binDongKim

**Comment by binDongKim** [comment]
Esc key clearing should already work with the `ppSearchInput` directive because it's already implemented there. It works in my local.

**Comment by yjqg6666** [comment]
Not working in my fresh build from master. Press ESC key only get the focus lost.
image

**Comment by yjqg6666** [comment]
It's also not working in an app's page.
image

**Comment by yjqg6666** [comment]
I found out the reason. If i disable the cVim plugin on the domain (in Chrome), it's working. 
I wonder why "(keydown.esc)" is working while ppSearchInput don't.

**Comment by yjqg6666** [comment]
cVim is not available on Chrome Web Store, but can be downloaded from https://github.com/1995eaton/chromium-vim.

**Comment by binDongKim** [comment]
@yjqg6666 I'll look into it. Thanks for the report.

**Comment by binDongKim** [comment]
@yjqg6666 I'll close this and dig into the relation between the cVim and angular later.

**Pull request closed without merging**
