### PR TITLE
Add mariadb plugin #1388

### PR DESCRIPTION
**Pull request by dawidmalina**

### CODE REVIEW

**Comment by dawidmalina** [comment]
mariadb-pinpoint

**Comment by nstopkimsk** [comment]
@lioolli please review this pr.

**Comment by lioolli** [comment]
There're some issues with your tests.

1. move MariaDBTest to pinpoint-agent module. PinpointPluginTestSuite must be run after agent is built. Maybe init.sql file should go to pinpoint-agent too, then please put it under 'mariadb' directory not 'sql' to seperate plugin test resources per plugin.

2. add following annotations to MariaDBTest. 
 ```
 @JvmVersion(7)
 @Repository("http://jcenter.bintray.com")
 ```
 If you don't specify @JvmVersion, it runs test with Java 6, which cannot load mariadb classes complied by JVM 7. Because mariaDB4j is not in maven central repository, you have to specify @Repository too.


3. change database name in init.sql to 'test' not 'TEST'
When I run the test, it failed with `ERROR 1049 (42000) at line 1: Unknown database 'TEST'`

**Comment by dawidmalina** [comment]
I will apply your suggestions later. Or I can remove this test totally. This test was useful only during debugging. What do you think?

**Comment by lioolli** [comment]
I'm working on plugin pr check list now. One of the requirements is **At least one plugin test**. Even if nobody changes the plugin code, we need this test because agent(common, bootstrap, bootstrap-core, profiler module)  modification can cause plugin failure.

**Comment by lioolli** [comment]
Merged with #1503

**Pull request closed without merging**
