### PR TITLE
[#noissue] fix typo : HbaseTableConstatns to HbaseTableConstants

### PR DESCRIPTION
**Pull request by tlqaksqhr**
fix typo : HbaseTableConstatns to HbaseTableConstants and HbaseTableConstatns.java to HbaseTableConstants.java

### CODE REVIEW

**Comment by RoySRose** [comment]
Hello, @tlqaksqhr 

Thank you for your first-time contribution.
I agree with you on fixing the typo.

Also, like to ask you.
Have you tested it after fixing the names?

**Comment by RoySRose** [comment]
Also, like to point out.

You should merge the 3commits in to one.

**Comment by tlqaksqhr** [comment]
> Hello, @tlqaksqhr
> 
> Thank you for your first-time contribution.
> I agree with you on fixing the typo.
> 
> Also, like to ask you.
> Have you tested it after fixing the names?

Well, I tested changed code by using “./mvnw clean install -DskipTests=false”.

Then, the test result is same as master branch(= before I changed code).
(Test is failed at the same position)

**Comment by tlqaksqhr** [comment]
> Also, like to point out.
> 
> You should merge the 3commits in to one.

Merging 3 commit to 1 commit.
Thank you for checking.

**Comment by RoySRose** [comment]
>Well, I tested changed code by using “./mvnw clean install -DskipTests=false”.
Then, the test result is same as master branch(= before I changed code).
(Test is failed at the same position)

The test might not represent that it is okay(ESPECIALLY if the test was originally failing), since we are not sure that the test for the changes even exists.

I've also looked into the changes and doubt that it will cause any problem.
But highly recommend that the it will be tried.
I believe you need to set the environment anyway.

**Comment by RoySRose** [comment]
Please change the header of the commit and add [#noissue] as below

image

**Comment by tlqaksqhr** [comment]
@RoySRose 
I changed commit header and title.
Thanks for reviewing.

**Pull request merged**
