### PR TITLE
Websphere plugin

### PR DESCRIPTION
**Pull request by sjmittal**
the pull request is for websphere plugin.
there is also an experimental plugin axis2-jaxws to intercept webservices requests using axis2-jaxws.

### CODE REVIEW

**Comment by Xylus** [comment]
@sjmittal Thanks for the work! Looks like the branch needs some cleaning up like you said.
Could you give edit permission to maintainers as shown [here](../pull/2001#issuecomment-252404329)?

**Comment by sjmittal** [comment]
@Xylus  I have checked the Allow edits from maintainers. box as mentioned.

**Comment by Xylus** [comment]
@sjmittal Thank you, will work on this after 1.6.0 releases (targeting for 1.6.1)

**Comment by jaehong-kim** [comment]
* Separate Apache Axis2 and IBM WebSphere and register for each PR.
   * Include unmodified files, please clean up.
* In the WebSpherePlugin, the com.ibm.ws.webcontainer.jar file is used and needs to be verified if the file is allowed to be redistributed.
* Describe why you use RESOLVE_CLASS in the PlainClassLoaderHandler class.
~~~
Class<?> clazz =  (Class<?>)DEFINE_CLASS.invoke(classLoader, ct.getName(), bytes, 0, bytes.length);
RESOLVE_CLASS.invoke(classLoader, clazz);
return clazz;
~~~
* Why did you modify the URLClassLoaderHandler class to use LOAD_CLASS?
~~~
return (Class<?>) LOAD_CLASS.invoke(classLoader, className, true);
~~~

**Comment by sjmittal** [comment]
Separate Apache Axis2 and IBM WebSphere and register for each PR.
        Include unmodified files, please clean up.
Note clear on which files need cleanup and how to register different PR.

    In the WebSpherePlugin, the com.ibm.ws.webcontainer.jar file is used and needs to be verified if the file is allowed to be redistributed.

I am not sure if this can be redistributed. Note sure ibm allows this. Please suggest the alternative, this jar however needs to be in plugins/lib dir to make sure plugin classes are compiled.

    Describe why you use RESOLVE_CLASS in the PlainClassLoaderHandler class.

Class<?> clazz =  (Class<?>)DEFINE_CLASS.invoke(classLoader, ct.getName(), bytes, 0, bytes.length);
RESOLVE_CLASS.invoke(classLoader, clazz);
return clazz;

Ok this one is tricky. What I found in some instances that if I don't resolve class, it is not found during the instrumentation phase. After adding this line it worked fine. Could you please discuss this as having resolve class would cause issues?
    Why did you modify the URLClassLoaderHandler class to use LOAD_CLASS?

return (Class<?>) LOAD_CLASS.invoke(classLoader, className, true);

Could you please check the latest changes, I think this line is no more included in URLClassLoaderHandler . Please point to line number. I remember removing this line in subsequent commit.

**Comment by sjmittal** [comment]
On the last point when I added my code
the original line was 
commit id - (339ca28bb2cd52f23f3da343b34454417025559d)
(Class<T>) urlClassLoader.loadClass(className);

I changed it to 
return (Class<?>) LOAD_CLASS.invoke(classLoader, className, true);

I may have done this because later was working for me.  Is there any difference between the two and if we use my code, is there any issues.

I guess if you want to use my code then line 67 would change to
return (Class<T>) urlClassLoader.loadClass(className);
to
return (Class<T>) LOAD_CLASS.invoke(classLoader, className, true);

**Comment by emeroad** [comment]
I suggest a compiler trick.

Compiler trick example is in the pinpoint-optional module.
- [IBM OperatingSystemMXBean.java](https://github.com/naver/pinpoint/blob/master/profiler-optional/profiler-optional-jdk7/src/main/java-ibm/com/ibm/lang/management/OperatingSystemMXBean.java)  <- Complie stub class
This class does not include jar packaging.
It is used only at compile time.

packaing [pom.xml](https://github.com/naver/pinpoint/blob/master/profiler-optional/profiler-optional-parent/pom.xml) setting

Create the following class stub for the compiler trick.
**com.ibm.websphere.servlet.request.IRequest** 
**com.ibm.websphere.servlet.response.IResponse**  ...
If you compile with two stub class. you don't need websphere.jar.

**Comment by sjmittal** [comment]
I have resolved all the issues mentioned so this can be merged.
The two point of contentions are:

- Describe why you use RESOLVE_CLASS in the PlainClassLoaderHandler class.

```
Class<?> clazz =  (Class<?>)DEFINE_CLASS.invoke(classLoader, ct.getName(), bytes, 0, bytes.length);
RESOLVE_CLASS.invoke(classLoader, clazz);
return clazz;
```

- Why did you modify the URLClassLoaderHandler class to use LOAD_CLASS?

`return (Class<?>) LOAD_CLASS.invoke(classLoader, className, true);`

I have added my comments inline in the code and also described above for these 2 changes.

Let me know if anything else is needed before this can be merged.

**Comment by jaehong-kim** [comment]
Hi @sjmittal 
* The jar file does not contain META-INF.
Add the following to the maven-jar-plugin in the plugins/websphere/pom.xml file.
~~~
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-jar-plugin</artifactId>
    <configuration>
        <includes>
            <include>com/navercorp/**/*</include>
            <include>META-INF/**/*</include> <!--  -->
        </includes>
    </configuration>
</plugin>
~~~
* ServiceType 1040/1041 is already in use by JBossPlugin. 
Please correct it to another number. e.g. 1060/1061
* Clean up your commit log into logical chunks of work to make it easier for us to figure out what and why you've changed something. (git rebase -i helps)
* This PR branch has conflict.
Please resolve conflict.
 Or Could you please give me **maintainer permission**
- https://github.com/blog/2247-improving-collaboration-with-forks
  2b17b4c2-7444-11e6-8959-2f7ed2012d07

**Comment by sjmittal** [comment]
@jaehong-kim 
-     The jar file does not contain META-INF.

Done.    

-     ServiceType 1040/1041 is already in use by JBossPlugin.

Done

-    Clean up your commit log into logical chunks of work to make it easier for us to figure out what and why you've changed something. (git rebase -i helps)

I did that and I am attaching the output.
[f3v43cxw.yht.txt](https://github.com/naver/pinpoint/files/749537/f3v43cxw.yht.txt)
State of my branch is  (cpu_monitoring_fix|REBASE-i 1/28)
So I guess I need to resolve conflicts in 28 stages, which may take a while. Would it be easier to just merge master into this branch again?

-     This PR branch has conflict.

I had merged master to this branch a while back. I have already provided you with maintainer permission. Please check. Let me know if you can resolve conflicts or if should I attempt the same. In that case please let me know if I should use rebase or merge.


I know this PR is a mess, I guess whenever I fork I should make a point to periodically rebase with master to avoid such things in future.

**Comment by jaehong-kim** [comment]
@sjmittal Thank you for your contribution.
I will be able to look at it after I complete the development in progress.

**Comment by sjmittal** [comment]
@jaehong-kim @Xylus @emeroad 
Could you please let us know the merge status of this PR. It is showing some conflicts however when I run
https://github.com/naver/pinpoint/compare/master...sjmittal:cpu_monitoring_fix
It gives me Able to merge

Since this PR had few changes like 
100755 → 100644
No changes.
I created another PR this time just rebasing websphere related changes between these two branches.
https://github.com/naver/pinpoint/compare/master...sjmittal:master
https://github.com/naver/pinpoint/pull/2614
The PR again shows cannot be rebased due to conflicts however if we just do the diff between branches it says Able to merge.

So I am bit confused as what is causing this conflicts, from my side I have tried to resolve any issues. Please let me know if anything more is to be done.

If you follow both the PR they only have webspehe related changes, plus two changes for URLClassLoaderHandler and PlainClassLoaderHandler where I added some additional code to load classes. If you feel these are not needed you can undo these commits and we can again review them.

**Comment by jaehong-kim** [comment]
I have cleaned up the code.
* Apache Axis2 detach.
* The PlainClassLoaderHandler class does not use the resloveClass () method.
* testapp's test code has been removed.

Please review.
https://github.com/naver/pinpoint/pull/2933

**Comment by emeroad** [comment]
merged : #2933

**Pull request closed without merging**
