### PR TITLE
[#4418] Add Druid Plugin

### PR DESCRIPTION
**Pull request by VictorZeng**
Title: Druid Plugin Contribution

Link: https://github.com/VictorZeng/pinpoint/tree/druid-plugin/plugins/druid
Target: pinpoint-druid-plugin
Supported Version: All Druid version.
Description: Druid is a database connection pool from Alibaba inc.

ServiceTypes: (6062, "DRUID")
Annotations:
Configurations:
profiler.jdbc.druid=true
profiler.jdbc.druid.connectionclose=true

### CODE REVIEW

**Comment by VictorZeng** [comment]
fix #4418

**Comment by VictorZeng** [comment]
44183578-1ceae300-a13e-11e8-8955-25f911605fc3

**Comment by VictorZeng** [comment]
44183686-87038800-a13e-11e8-82dc-74977a1505ca

**Comment by Xylus** [comment]
@VictorZeng 
Thank you for your contribution.
Your PR looks good, could you resolve the conflict?

**Comment by VictorZeng** [comment]
@Xylus OK, I will commit a new PR.

**Pull request closed without merging**
